export const EMAIL_CHANGED= 'email_changed'
export const PASSWORD_CHANGED= 'password_changed'
export const ERROR_MESSAGE = 'error_message'
export const CLEAR_ERROR = 'clear_error'
export const LOADING = 'loading'
export const AUTH_TOKEN= 'auth_token'
export const LOGIN_USER_SUCCESS = 'login_user_success'